### ISSUE TITLE
Uncaught Error: Element type is invalid: 

### ISSUE THREAD

**Issue by RockyKev** [wptrainingteam/devblog-dataviews-plugin#2]
> Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

I'm using `wp-env start` to kick up a docker server. Uncertain if it's related.

How to recreate:

1. Set up this project using `"@wordpress/dataviews": "^4.4.0"`
2. `npm i` to install that newer version
3. Visit that option page `http://localhost:8888/wp-admin/upload.php?page=add-media-from-third-party-service`
4. Click on the 3 dots under Actions.
5. The app crashes and the error appears in devtools console.

The current project is using @wordpress/dataviews 4.2.0, and that version works.

**Comment by Tropicalista** [comment]
This happens also if you try with WP 6.7

**Comment by oandregal** [comment]
👋 @RockyKev This is a known issue: the example plugin, as it is, it's not compatible with all WordPress/Gutenberg versions.

A fix (with the explanation) has landed in Gutenberg as of https://github.com/WordPress/gutenberg/pull/66825 and it'll take one week or two to be released. I'll update this plugin when it does.

**Comment by oandregal** [comment]
An updated on this: we just landed https://github.com/wptrainingteam/devblog-dataviews-plugin/pull/3 and this should be fixed. I manually tested it with WordPress 6.6 and WordPress 6.7, with and without the latest Gutenberg plugin active.

@RockyKev would you be able to confirm it works for you?
